name: "Pull Request Labeler"

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Labeler
        uses: actions/labeler@v5
        env:
          TOC_ISSUES: "${{ secrets.TOC_ISSUES }}"
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.TOC_ISSUES }}"
